import Footer from "./component/Footer";
import NavigasiBar from "./component/Navbar";
import { Toaster } from "react-hot-toast";

import "./globals.css";

export const metadata = {
  title: "Fakestore.com",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavigasiBar />
        <Toaster />

        {children}
        <Footer />
      </body>
    </html>
  );
}
